/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-bright": "#fcf9f2",
        "background": "#fcf9f2",
        "inverse-surface": "#31312c",
        "outline": "#737973",
        "surface-tint": "#4d6453",
        "on-tertiary-container": "#b18d48",
        "surface-container-high": "#ebe8e1",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#e9c176",
        "inverse-on-surface": "#f3f0ea",
        "surface-variant": "#e5e2db",
        "on-error": "#ffffff",
        "primary-container": "#1b3022",
        "on-primary-container": "#819986",
        "on-tertiary-fixed": "#261900",
        "secondary": "#7b5455",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdea5",
        "inverse-primary": "#b4cdb8",
        "secondary-fixed": "#ffdad9",
        "tertiary": "#211500",
        "on-secondary-container": "#7a5354",
        "surface-container-highest": "#e5e2db",
        "surface": "#fcf9f2",
        "primary-fixed": "#d0e9d4",
        "on-background": "#1c1c18",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#0b2013",
        "on-secondary-fixed-variant": "#613d3e",
        "on-secondary-fixed": "#2f1314",
        "on-primary": "#ffffff",
        "secondary-container": "#fecbcb",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#ecbaba",
        "on-surface": "#1c1c18",
        "on-error-container": "#93000a",
        "outline-variant": "#c3c8c1",
        "primary": "#061b0e",
        "surface-dim": "#dcdad3",
        "primary-fixed-dim": "#b4cdb8",
        "tertiary-container": "#3a2800",
        "on-primary-fixed-variant": "#364c3c",
        "surface-container": "#f0eee7",
        "on-tertiary-fixed-variant": "#5d4201",
        "on-surface-variant": "#434843",
        "surface-container-low": "#f6f3ec",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        // 'full' debe ser un círculo perfecto (avatares de Plantas Exóticas,
        // pin del mapa, botón de WhatsApp). Antes estaba a 0.75rem (12px).
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "80px",
        "container-max": "1280px",
        "section-gap": "120px",
        "gutter": "24px",
        "unit": "8px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display", "serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        headline: ["Playfair Display", "serif"],
        body: ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
